[theme]
base = "light"
primaryColor = "#c99326"
backgroundColor = "#f4f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#141a2e"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
